# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (hashicorp/ghaction-import-gpg) that assumes you set your
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `GPG_PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: release
on:
  push:
    tags:
      - 'v*'
jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: git tag $(cat VERSION)
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 1.9.1
      - name: Describe plugin
        id: plugin_describe
        run: echo "::set-output name=api_version::$(go run . describe | jq -r '.api_version')"
      - name: Install packer-pdc
        run: go get github.com/hashicorp/packer-plugin-sdk/cmd/packer-sdc@latest
      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --single-target --snapshot --clean
        env:
          PACKER_CI_PROJECT_API_VERSION: ${{ steps.plugin_describe.outputs.api_version }}
